//document.getElementById("PhoneNumberButton").onclick = ....
//document.getElementById("hobbyButton").onclick = ....
//document.getElementById("cityButton").onclick = ....
//document.getElementById("hobbyCountButton").onclick = ....
//document.getElementById("AllZipsButton").onclick = ....
//document.getElementById("hobbyButton").onclick = ....

function getAllPersons(number){}
